Repository ioskrew/SwiftLayout, pull requests merged in 2022-07, with the labels that each got.

#227 add comments for anchor combinating functions
  Sources/SwiftLayout/Core/Anchors/Anchors.swift
Labels: documentation

#226 View printer congifuration
  Sources/SwiftLayoutUtil/Describe/ConfigurablePropertys/ConfigurableProperty.swift
  Sources/SwiftLayoutUtil/Describe/ConfigurablePropertys/CustomConfigurablePropertys.swift
  Sources/SwiftLayoutUtil/Describe/Describer/ViewDescriber.swift
  Sources/SwiftLayoutUtil/Describe/Token/ViewToken.swift
  Sources/SwiftLayoutUtil/Extension/Configuration/NSLayoutConstraint+Configuration.swift
  Sources/SwiftLayoutUtil/Extension/Configuration/NSLineBreakMode+Configuration.swift
  Sources/SwiftLayoutUtil/Extension/Configuration/NSTextAlignment+Configuration.swift
  Sources/SwiftLayoutUtil/Extension/Configuration/Optional+Configuration.swift
  Sources/SwiftLayoutUtil/Extension/Configuration/UIAccessibilityTraits+Configuration.swift
  Sources/SwiftLayoutUtil/Extension/Configuration/UIBaselineAdjustment+Configuration.swift
  Sources/SwiftLayoutUtil/Extension/Configuration/UIButton+Configuration.swift
  Sources/SwiftLayoutUtil/Extension/Configuration/UIControl+Configuration.swift
  Sources/SwiftLayoutUtil/Extension/Configuration/UISemanticContentAttribute+Configuration.swift
  Sources/SwiftLayoutUtil/Extension/Configuration/UIStackView+Configuration.swift
  Sources/SwiftLayoutUtil/Extension/Configuration/UIView+Configuration.swift
  Tests/SwiftLayoutUtilTests/ViewPrinterTests.swift
Labels: enhancement, in progressing

#228 Add combination anchor
  Sources/SwiftLayout/Core/Anchors/Anchors.swift
Labels: enhancement

#229 [renaming] defualt -> default
  Sources/SwiftLayoutUtil/Describe/ConfigurablePropertys/ConfigurableProperty.swift
  Tests/SwiftLayoutUtilTests/ViewPrinterTests.swift
Labels: rename

#231 Change the configuration output of UIImage, UIFont, and UIColor to mu…
  Sources/SwiftLayoutUtil/Extension/Configuration/Optional+Configuration.swift
  Tests/SwiftLayoutUtilTests/ViewPrinterTests.swift
Labels: enhancement
