Repository ioskrew/SwiftLayout, pull requests merged in 2022-04, with the labels that each got.

#203 improving for IdentifierUpdater
  Sources/SwiftLayoutUtil/IdentifierUpdater.swift
  Sources/SwiftLayoutUtil/ViewPrinter.swift
Labels: enhancement

#206 hotfix/2.5.1
  Sources/SwiftLayout/Core/Layout/LayoutElements.swift
  Sources/SwiftLayoutUtil/LayoutPrinter.swift
Labels: bug

#209 Feature/distribute tests
  Package.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutUtilTests/IdentifierUpdaterTests.swift
  Tests/SwiftLayoutUtilTests/LayoutPrinterTests.swift
  Tests/SwiftLayoutUtilTests/Util/Extensions.swift
  Tests/SwiftLayoutUtilTests/ViewPrinterTests.swift
Labels: test

#208 suggest upper/lower case rules for README
  README.md
Labels: documentation

#210 remove dependencies of other libraries from tests
  Package.swift
  Tests/SwiftLayoutTests/AnchorsDSLTests.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/ImplementationTests/AnchorsImplementationTests.swift
  Tests/SwiftLayoutTests/ImplementationTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/ImplementationTests/ReferenceTests.swift
  Tests/SwiftLayoutTests/InterfaceTests/AnchorsDSLTests.swift
  Tests/SwiftLayoutTests/InterfaceTests/LayoutDSLTests.swift
  Tests/SwiftLayoutTests/InterfaceTests/LayoutableTests.swift
  Tests/SwiftLayoutTests/LayoutBuildingTests.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
  Tests/SwiftLayoutTests/Util/Attribute+CaseIterable.swift
  Tests/SwiftLayoutTests/Util/CallCountView.swift
  Tests/SwiftLayoutTests/Util/Extensions.swift
  Tests/SwiftLayoutTests/Util/XCTestCase+Context.swift
  Tests/SwiftLayoutUtilTests/IdentifierUpdaterTests.swift
  Tests/SwiftLayoutUtilTests/ViewPrinterTests.swift
Labels: test, in progressing

#215 improving testing
  Tests/SwiftLayoutTests/ImplementationTests/AnchorsImplementationTests.swift
  Tests/SwiftLayoutTests/InterfaceTests/AnchorsDSLTests.swift
  Tests/SwiftLayoutTests/InterfaceTests/LayoutDSLTests.swift
  Tests/SwiftLayoutTests/InterfaceTests/LayoutableTests.swift
  Tests/SwiftLayoutTests/Util/XCTViewAssert.swift
  Tests/SwiftLayoutTests/Util/XCTestCase+Context.swift
Labels: enhancement, test

#217 no more tabbed on tests
  Sources/SwiftLayoutUtil/Describe/Describer/ViewDescriber.swift
  Tests/SwiftLayoutUtilTests/Util/Extensions.swift
  Tests/SwiftLayoutUtilTests/ViewPrinterTests.swift
Labels: enhancement, test

#216 fix only identifier option for view printer
  Sources/SwiftLayoutUtil/Describe/Tag/ViewTags.swift
  Sources/SwiftLayoutUtil/Describe/Token/ViewToken.swift
  Tests/SwiftLayoutUtilTests/ViewPrinterTests.swift
Labels: bug

#220 remove deprecated method in Layoutable
  Sources/SwiftLayout/Layoutable/Layoutable.swift
Labels: enhancement

#222 Add priority method to anchors
  Sources/SwiftLayout/Core/Anchors/Container/AnchorsContainer.swift
  Sources/SwiftLayout/Core/Anchors/Elements/AnchorsConstraintProperty.swift
  Sources/SwiftLayout/Core/Anchors/Elements/AnchorsExpression.swift
  Tests/SwiftLayoutTests/ImplementationTests/AnchorsImplementationTests.swift
Labels: enhancement
