Repository ioskrew/SwiftLayout, pull requests merged in 2022-02, with the labels that each got.

#24 ConstraintBuilder.Binding을 통한 constraint의 연결
  Sources/SwiftLayout/Layout/Constraint/Builder/ConstraintBuilder.swift
  Sources/SwiftLayout/Layout/Constraint/ConstraintLayout.swift
  Sources/SwiftLayout/Layout/Constraint/Extension/UIView+Constraint.swift
  Sources/SwiftLayout/Layout/Constraint/Protocol/Constraint.swift
  Tests/SwiftLayoutTests/ConstraintTests.swift
Labels: enhancement

#30 Layout의 업데이트가 가능한 LayoutBuilding 추가
  Sources/SwiftLayout/Constraint/ConstraintLayout.swift
  Sources/SwiftLayout/External/LayoutBuilding.swift
  Tests/SwiftLayoutTests/LayoutBuildingTests.swift
  Tests/SwiftLayoutTests/LayoutUpdateTests.swift
Labels: enhancement

#36 프리뷰 개선
  README.md
  Sample/SwiftLayoutSample/SwiftLayoutSample/ViewController.swift
  Sources/SwiftLayout/Building/LayoutBuilding+SwiftUI.swift
Labels: enhancement

#38 프로토콜 명칭 개선
  Sources/SwiftLayout/Constraint/ConstraintLayout.swift
  Sources/SwiftLayout/Layout/Extension/Layout+Description.swift
  Sources/SwiftLayout/Layout/Extension/Optional+Layout.swift
  Sources/SwiftLayout/Layout/Layouts/ViewLayout.swift
  Sources/SwiftLayout/Layout/Protocol/ContainableLayout.swift
  Sources/SwiftLayout/Layout/Protocol/ViewContainableLayout.swift
Labels: enhancement

#41 Anchor!
  Sources/SwiftLayout/Constraint/Anchor.swift
  Sources/SwiftLayout/Constraint/Builder/ConstraintBuilder.swift
  Sources/SwiftLayout/Constraint/ConstraintLayout.swift
  Sources/SwiftLayout/Constraint/Extension/UIView+Constraint.swift
  Sources/SwiftLayout/Constraint/Protocol/ConstraintCreating.swift
  Tests/SwiftLayoutTests/ConstraintTests.swift
  Tests/SwiftLayoutTests/LayoutBuildingTests.swift
Labels: enhancement

#49 hiding of Activation class from external of library
  Sample/SwiftLayoutSample/SwiftLayoutSample.xcodeproj/project.pbxproj
  Sample/SwiftLayoutSample/SwiftLayoutSample/Base.lproj/Main.storyboard
  Sample/SwiftLayoutSample/SwiftLayoutSample/LayoutHostingViewController.swift
  Sample/SwiftLayoutSample/SwiftLayoutSample/ViewController.swift
  Sources/SwiftLayout/Building/LayoutBuilding.swift
  Sources/SwiftLayout/Layout/Layouts/Activation.swift
  Sources/SwiftLayout/Layout/Protocol/Layout.swift
  Tests/SwiftLayoutTests/DSLTests.swift
  Tests/SwiftLayoutTests/LayoutBuildingTests.swift
Labels: enhancement

#50 add Deactivatable protocol
  Sample/SwiftLayoutSample/SwiftLayoutSample/LayoutHostingViewController.swift
  Sample/SwiftLayoutSample/SwiftLayoutSample/ViewController.swift
  Sources/SwiftLayout/Building/LayoutBuilding.swift
  Sources/SwiftLayout/Layout/Layouts/Activation.swift
  Sources/SwiftLayout/Layout/Layouts/AnyDeactivatable.swift
  Sources/SwiftLayout/Layout/Protocol/Deactivatable.swift
  Sources/SwiftLayout/Layout/Protocol/Layout.swift
  Tests/SwiftLayoutTests/AnchorsTests.swift
  Tests/SwiftLayoutTests/DSLTests.swift
  Tests/SwiftLayoutTests/ImplementationTest.swift
  Tests/SwiftLayoutTests/LayoutViewTreeTests.swift
Labels: enhancement

#63 UILayoutGuide
  Sources/SwiftLayout/Anchors/Anchors.swift
  Sources/SwiftLayout/Anchors/Protocol/ConstraintItem.swift
  Sources/SwiftLayout/Layout/Protocol/Layout.swift
  Sources/SwiftLayout/Util/TagDescriptor.swift
  Sources/SwiftLayout/Util/WeakReference.swift
  Tests/SwiftLayoutTests/ImplementationTest.swift
Labels: enhancement

#66 update minimum tool chain version
  Package.swift
Labels: enhancement

#79 update github action
  .github/workflows/swift.yml
Labels: enhancement

#78 suppress fatal error from LayoutImp
  Sources/SwiftLayout/Layout/Implementation/LayoutImp.swift
Labels: question

#87 - identifying before constraint process
  Sources/SwiftLayout/Layout/Implementation/Activator.swift
Labels: enhancement

#89 improvement/anchors
  README.md
  Sources/SwiftLayout/Anchors/Implementation/Anchors.swift
  Sources/SwiftLayout/Layout/Implementation/LayoutImp.swift
  Tests/SwiftLayoutTests/DSLTests.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
  Tests/SwiftLayoutTests/XCTest/XCTestCase+Context.swift
Labels: enhancement

#94 layout now has multiple root layouts
  Sources/SwiftLayout/Building/LayoutBuilding.swift
  Sources/SwiftLayout/Extension/NSLayoutConstraint+Constraint.swift
  Sources/SwiftLayout/Layout/Implementation/Activator.swift
  Sources/SwiftLayout/Layout/Implementation/LayoutImp.swift
  Sources/SwiftLayout/Layout/Protocol/Layout.swift
  Tests/SwiftLayoutTests/AnchorsDSLTest.swift
Labels: enhancement, question

#95 concrete layout types
  README.md
  Sources/SwiftLayout/Anchors/Implementation/Anchors.swift
  Sources/SwiftLayout/Anchors/Protocol/Constraint.swift
  Sources/SwiftLayout/Builder/AnchorsBuilder.swift
  Sources/SwiftLayout/Builder/LayoutBuilder.swift
  Sources/SwiftLayout/Building/AnyLayoutBuilding.swift
  Sources/SwiftLayout/Building/LayoutBuilding.swift
  Sources/SwiftLayout/Layout/Implementation/Activator.swift
  Sources/SwiftLayout/Layout/Implementation/Deactivation.swift
  Sources/SwiftLayout/Layout/Implementation/LayoutImp.swift
  Sources/SwiftLayout/Layout/Implementation/Layouts/AnchorsLayout.swift
  Sources/SwiftLayout/Layout/Implementation/Layouts/AnyLayout.swift
  Sources/SwiftLayout/Layout/Implementation/Layouts/ArrayLayout.swift
  Sources/SwiftLayout/Layout/Implementation/Layouts/ConditionalLayout.swift
  Sources/SwiftLayout/Layout/Implementation/Layouts/EmptyLayout.swift
  Sources/SwiftLayout/Layout/Implementation/Layouts/OptionalLayout.swift
  Sources/SwiftLayout/Layout/Implementation/Layouts/SublayoutLayout.swift
  Sources/SwiftLayout/Layout/Implementation/Layouts/TupleLayout.swift
  Sources/SwiftLayout/Layout/Implementation/Layouts/ViewLayout.swift
  Sources/SwiftLayout/Layout/Implementation/ViewInformation.swift
  Sources/SwiftLayout/Layout/LayoutBuilder.swift
  Sources/SwiftLayout/Layout/Protocol/Layout.swift
  Tests/SwiftLayoutTests/ImplementationTest.swift
  Tests/SwiftLayoutTests/LayoutBuildingTest.swift
  Tests/SwiftLayoutTests/LayoutDSLTest.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
  Tests/SwiftLayoutTests/Util/Weakesn.swift
Labels: enhancement

#100 SwiftLayoutPrinter now print sublayout instead of subviews
  Sources/SwiftLayout/Printing/SwiftLayoutPrinter.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
Labels: enhancement

#102 add extensions for Anchors
  Sources/SwiftLayout/Extension/Anchor+Convenience.swift
  Tests/SwiftLayoutTests/AnchorsDSLTest.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
  Tests/SwiftLayoutTests/Util/Extensions.swift
Labels: enhancement

#103 Add setMultiplier method to anchor
  Sources/SwiftLayout/Components/Anchors/Anchors.swift
  Sources/SwiftLayout/Components/Anchors/Constraint.swift
  Tests/SwiftLayoutTests/ImplementationTest.swift
Labels: enhancement

#104 anchors from layoutanchor
  Sources/SwiftLayout/Components/Anchors/Anchors.swift
  Sources/SwiftLayout/Components/Anchors/LayoutAnchor.swift
  Sources/SwiftLayout/Extension/UIView+LayoutAnchor.swift
  Tests/SwiftLayoutTests/AnchorsDSLTest.swift
Labels: enhancement

#105 anydeactivable
  Sources/SwiftLayout/Components/Activator/AnyDeactivable.swift
  Sources/SwiftLayout/Components/Activator/Deactivation.swift
  Sources/SwiftLayout/Components/Layout/Layout.swift
  Sources/SwiftLayout/Components/Layout/ViewInformation.swift
  Tests/SwiftLayoutTests/ImplementationTest.swift
  Tests/SwiftLayoutTests/LayoutDSLTest.swift
Labels: enhancement

#106 add SwiftLayoutViewConfiguration
  Sources/SwiftLayout/Extension/Set+AnyDeactivable.swift
  Sources/SwiftLayout/Extension/UIVIew+Layout.swift
  Tests/SwiftLayoutTests/LayoutDSLTest.swift
Labels: enhancement

#109 add final active
  README.md
  Sources/SwiftLayout/Components/Activator/Activator.swift
  Sources/SwiftLayout/Components/Anchors/Anchors.swift
  Sources/SwiftLayout/Components/Anchors/Constraint.swift
  Sources/SwiftLayout/Components/Layout/Layout.swift
  Tests/SwiftLayoutTests/AnchorsDSLTest.swift
  Tests/SwiftLayoutTests/ImplementationTest.swift
  Tests/SwiftLayoutTests/LayoutBuildingTest.swift
  Tests/SwiftLayoutTests/LayoutDSLTest.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
  Tests/SwiftLayoutTests/Util/Extensions.swift
Labels: enhancement

#110 simple bug fix
  Sources/SwiftLayout/Components/Activator/Activator.swift
Labels: bug

#114 update traverse logics for empty layout and UIView
  Sources/SwiftLayout/Components/Activator/Activator.swift
  Sources/SwiftLayout/Components/Layout/Layout.swift
  Sources/SwiftLayout/Components/Layout/Layouts/ViewLayout.swift
  Sources/SwiftLayout/Extension/UIVIew+Layout.swift
  Tests/SwiftLayoutTests/LayoutDSLTest.swift
Labels: bug

#115 some fixes
  Sources/SwiftLayout/Components/Layout/ViewInformation.swift
  Sources/SwiftLayout/Printing/SwiftLayoutPrinter.swift
  Sources/SwiftLayout/Util/IdentifierUpdater.swift
  Tests/SwiftLayoutTests/LayoutDSLTest.swift
Labels: bug, enhancement

#116 improve updating
  Sources/SwiftLayout/Components/Activator/Activator.swift
  Sources/SwiftLayout/Components/Activator/AnyDeactivable.swift
  Sources/SwiftLayout/Components/Activator/Deactivation.swift
  Sources/SwiftLayout/Components/Layout/ViewInformation.swift
  Sources/SwiftLayout/Util/WeakReference.swift
  Tests/SwiftLayoutTests/AnchorsDSLTest.swift
  Tests/SwiftLayoutTests/ImplementationTest.swift
  Tests/SwiftLayoutTests/LayoutDSLTest.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
Labels: enhancement

#118 update test cases
  Sources/SwiftLayout/Printing/SwiftLayoutPrinter.swift
  Tests/SwiftLayoutTests/AnchorsDSLTests.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/LayoutBuildingTest.swift
  Tests/SwiftLayoutTests/LayoutBuildingTests.swift
  Tests/SwiftLayoutTests/LayoutDSLTest.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
Labels: enhancement

#122 fix infinite diggin in IdentifierUpdater
  Sources/SwiftLayout/Util/IdentifierUpdater.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
Labels: bug
