Repository ioskrew/SwiftLayout, pull requests merged in 2022-03, with the labels that each got.

#123 add GroupLayout
  Sources/SwiftLayout/Components/Layout/Layouts/GroupLayout.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
Labels: enhancement

#124 SwiftLayoutPrinter has flags not LayoutOptions
  Sources/SwiftLayout/Components/Activator/Activator.swift
  Sources/SwiftLayout/Printing/SwiftLayoutPrinter.swift
  Sources/SwiftLayout/Util/IdentifierUpdater.swift
  Sources/SwiftLayout/Util/TagDescriptor.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
Labels: enhancement

#126 add updateIdentifiers method
  Sources/SwiftLayout/Building/AnyLayoutBuilding.swift
  Sources/SwiftLayout/Building/LayoutBuilding.swift
  Sources/SwiftLayout/Components/Activator/Activator.swift
  Sources/SwiftLayout/Components/Activator/AnyDeactivable.swift
  Sources/SwiftLayout/Components/Activator/Deactivation.swift
  Sources/SwiftLayout/Components/Layout/Layout.swift
  Sources/SwiftLayout/Components/Layout/LayoutOptions.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
Labels: enhancement

#128 update layout without LayoutBuilding
  Sources/SwiftLayout/Components/Activator/Deactivable.swift
  Sources/SwiftLayout/Components/Layout/Layout.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
Labels: enhancement

#130 LayoutBuilder uses buildExpression to build UIView and Optional
  Sources/SwiftLayout/Components/Builder/LayoutBuilder.swift
  Sources/SwiftLayout/Extension/Optional+Layout.swift
  Sources/SwiftLayout/Extension/UIVIew+Layout.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
Labels: enhancement

#129 refactoring anchors
  Sources/SwiftLayout/Components/Anchors/Anchors.swift
  Sources/SwiftLayout/Extension/Anchors+Convenience.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
Labels: enhancement

#134 separate strong reference test from implementation tests
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/ReferenceTests.swift
Labels: enhancement

#135 using context function for reference test
  Tests/SwiftLayoutTests/ReferenceTests.swift
Labels: enhancement

#136 removing of user handling in SwiftLayout for animation
  README.md
  Sources/SwiftLayout/Building/LayoutBuilding.swift
  Sources/SwiftLayout/Components/Activator/Activator.swift
  Sources/SwiftLayout/Components/Layout/Layout.swift
  Sources/SwiftLayout/Components/Layout/Layouts/ViewLayout.swift
  Sources/SwiftLayout/Components/Layout/ViewInformation.swift
  Sources/SwiftLayout/Extension/Layout/UIVIew+Layout.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
  run-test.sh
Labels: enhancement

#137 remove deactivable and change deactivation to activation
  README.md
  Sources/SwiftLayout/Building/LayoutBuilding.swift
  Sources/SwiftLayout/Components/Activator/Activation.swift
  Sources/SwiftLayout/Components/Activator/Activator.swift
  Sources/SwiftLayout/Components/Activator/AnyDeactivable.swift
  Sources/SwiftLayout/Components/Activator/Deactivable.swift
  Sources/SwiftLayout/Components/Layout/Layout.swift
  Sources/SwiftLayout/Extension/Layout/Set+Activation.swift
  Tests/SwiftLayoutTests/AnchorsDSLTests.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/LayoutBuildingTests.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
  Tests/SwiftLayoutTests/ReferenceTests.swift
Labels: enhancement

#140 code cleanup for 2.0
  Sources/SwiftLayout/Components/Anchors/Anchors.swift
  Sources/SwiftLayout/Components/Layout/Layout.swift
  Sources/SwiftLayout/Components/Layout/Layouts/ViewLayout.swift
  Sources/SwiftLayout/Components/Layout/ViewInformation.swift
  Sources/SwiftLayout/Extension/Anchors/Anchors+Convenience.swift
  Sources/SwiftLayout/Extension/Layout/UIVIew+Layout.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
Labels: enhancement

#143 update readme
  README.md
Labels: documentation

#144 add center to Anchors
  Sources/SwiftLayout/Extension/Anchors/Anchors+Convenience.swift
Labels: enhancement

#146 Layout protocol redesign
  Sources/SwiftLayout/Components/Layout/Layout.swift
  Sources/SwiftLayout/Components/Layout/Layouts/AnchorsLayout.swift
  Sources/SwiftLayout/Components/Layout/Layouts/AnyLayout.swift
  Sources/SwiftLayout/Components/Layout/Layouts/ArrayLayout.swift
  Sources/SwiftLayout/Components/Layout/Layouts/ConditionalLayout.swift
  Sources/SwiftLayout/Components/Layout/Layouts/EmptyLayout.swift
  Sources/SwiftLayout/Components/Layout/Layouts/OptionalLayout.swift
  Sources/SwiftLayout/Components/Layout/Layouts/SublayoutLayout.swift
  Sources/SwiftLayout/Components/Layout/Layouts/TupleLayout.swift
  Sources/SwiftLayout/Components/Layout/Layouts/ViewLayout.swift
  Sources/SwiftLayout/Core/Activator/Activation.swift
  Sources/SwiftLayout/Core/Activator/Activator.swift
  Sources/SwiftLayout/Core/Anchors/Anchors.swift
  Sources/SwiftLayout/Core/Anchors/ConstraintableItem.swift
  Sources/SwiftLayout/Core/Builder/AnchorsBuilder.swift
  Sources/SwiftLayout/Core/Builder/LayoutBuilder.swift
  Sources/SwiftLayout/Core/Layout/Layout.swift
  Sources/SwiftLayout/Core/Layout/LayoutElements.swift
  Sources/SwiftLayout/Core/Layout/Layouts/AnyLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/ArrayLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/ConditionalLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/EmptyLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/GroupLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/OptionalLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/TupleLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/ViewLayout.swift
  Sources/SwiftLayout/Core/Layout/ViewInformation.swift
  Sources/SwiftLayout/Extension/Layout/UIVIew+Layout.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
Labels: enhancement

#145 readme 2.0
  README.md
  README_1.md
Labels: documentation

#120 add DocC
  Package.swift
  Sources/SwiftLayout/Core/Anchors/Anchors.swift
  Sources/SwiftLayout/Core/Layout/Layout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/ViewLayout.swift
  Sources/SwiftLayout/Extension/Anchors/Anchors+Convenience.swift
  Sources/SwiftLayout/Extension/Layout/UIVIew+Layout.swift
  Sources/SwiftLayout/Layoutable/PropertyWrapper/LayoutProperty.swift
  Sources/SwiftLayout/SwiftLayout.docc/Extensions/Components/Anchors.md
  Sources/SwiftLayout/SwiftLayout.docc/Extensions/Components/Layout.md
  Sources/SwiftLayout/SwiftLayout.docc/GettingStarted.md
  Sources/SwiftLayout/SwiftLayout.docc/Resources/images/swiftlayout-logo@2x.png
  Sources/SwiftLayout/SwiftLayout.docc/Resources/images/tutorials/document-capture.png
  Sources/SwiftLayout/SwiftLayout.docc/Resources/images/tutorials/name-to-documents.png
  Sources/SwiftLayout/SwiftLayout.docc/Resources/images/tutorials/select-app.png
  Sources/SwiftLayout/SwiftLayout.docc/SwiftLayout.md
  Sources/SwiftLayout/SwiftLayout.docc/Tutorials/codes/add-to-superview-1.swift
  Sources/SwiftLayout/SwiftLayout.docc/Tutorials/tutorial-create-project.tutorial
  Sources/SwiftLayout/SwiftLayout.docc/Tutorials/tutorial-table.tutorial
Labels: documentation

#153 support macOS from 10.15
  .github/workflows/swift.yml
  Package.swift
  Sources/SwiftLayout/Core/Activator/Activation.swift
  Sources/SwiftLayout/Core/Activator/Activator.swift
  Sources/SwiftLayout/Core/Anchors/Anchors.swift
  Sources/SwiftLayout/Core/Anchors/ConstraintableItem.swift
  Sources/SwiftLayout/Core/Builder/LayoutBuilder.swift
  Sources/SwiftLayout/Core/Layout/Layout.swift
  Sources/SwiftLayout/Core/Layout/LayoutElements.swift
  Sources/SwiftLayout/Core/Layout/Layouts/AnyLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/ArrayLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/ConditionalLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/EmptyLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/GroupLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/OptionalLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/TupleLayout.swift
  Sources/SwiftLayout/Core/Layout/Layouts/ViewLayout.swift
  Sources/SwiftLayout/Core/Layout/ViewInformation.swift
  Sources/SwiftLayout/Extension/Anchors/Anchors+Convenience.swift
  Sources/SwiftLayout/Extension/Kit/ViewAlias.swift
  Sources/SwiftLayout/Extension/Layout/Set+Activation.swift
  Sources/SwiftLayout/Extension/Layout/UIVIew+Layout.swift
  Sources/SwiftLayout/Extension/NSLayoutConstraint+Description.swift
  Sources/SwiftLayout/Layoutable/Layoutable+SwiftUI.swift
  Sources/SwiftLayout/Layoutable/Layoutable.swift
  Sources/SwiftLayout/Printing/SwiftLayoutPrinter.swift
  Sources/SwiftLayout/SwiftLayout.docc/Tutorials/codes/add-to-superview-1.swift
  Sources/SwiftLayout/Util/IdentifierUpdater.swift
  Sources/SwiftLayout/Util/TagDescriptor.swift
  Sources/SwiftLayout/Util/WeakReference.swift
  Tests/SwiftLayoutTests/AnchorsDSLTests.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/LayoutBuildingTests.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
  Tests/SwiftLayoutTests/ReferenceTests.swift
  Tests/SwiftLayoutTests/Util/Extensions.swift
  Tests/SwiftLayoutTests/Util/Tag.swift
  Tests/SwiftLayoutTests/Util/ViewAlias.swift
  Tests/SwiftLayoutTests/Util/Weakesn.swift
  Tests/SwiftLayoutTests/Util/XCTestCase+Context.swift
  run-test.sh
Labels: enhancement

#158 remove tutorial
  Sources/SwiftLayout/SwiftLayout.docc/Extensions/Components/Anchors.md
  Sources/SwiftLayout/SwiftLayout.docc/Extensions/Components/Layout.md
  Sources/SwiftLayout/SwiftLayout.docc/GettingStarted.md
  Sources/SwiftLayout/SwiftLayout.docc/Resources/images/swiftlayout-logo@2x.png
  Sources/SwiftLayout/SwiftLayout.docc/Resources/images/tutorials/document-capture.png
  Sources/SwiftLayout/SwiftLayout.docc/Resources/images/tutorials/name-to-documents.png
  Sources/SwiftLayout/SwiftLayout.docc/Resources/images/tutorials/select-app.png
  Sources/SwiftLayout/SwiftLayout.docc/SwiftLayout.md
  Sources/SwiftLayout/SwiftLayout.docc/Tutorials/codes/add-to-superview-1.swift
  Sources/SwiftLayout/SwiftLayout.docc/Tutorials/tutorial-create-project.tutorial
  Sources/SwiftLayout/SwiftLayout.docc/Tutorials/tutorial-table.tutorial
Labels: enhancement

#159 apply SL suffix to Layoutable
  Sources/SwiftLayout/Layoutable/Layoutable+SwiftUI.swift
  Sources/SwiftLayout/Layoutable/Layoutable.swift
  Sources/SwiftLayout/Layoutable/PropertyWrapper/LayoutProperty.swift
  Sources/SwiftLayout/Layoutable/Wrapper/LayoutableMethodWrapper.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/LayoutBuildingTests.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
  Tests/SwiftLayoutTests/ReferenceTests.swift
Labels: enhancement

#161 test/enchance anchors
  Sources/SwiftLayout/Extension/NSLayoutConstraint+Description.swift
  Sources/SwiftLayout/Extension/UILayoutGuide+Description.swift
  Tests/SwiftLayoutTests/AnchorsDSLTests.swift
  Tests/SwiftLayoutTests/Util/XCTestCase+Context.swift
Labels: test

#162 add options to SwiftLayoutPrinter
  Sources/SwiftLayout/Printing/SwiftLayoutPrinter.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
Labels: enhancement

#177 Contributing
  CONTRIBUTING.md
Labels: documentation

#181 improving of README
  README.md
  README_ko.md
Labels: documentation

#179 fix ambiguous use of Anchors.size
  Sources/SwiftLayout/Core/Anchors/Anchors.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
Labels: enhancement

#180 fix/swiftlayoutprinter
  Sources/SwiftLayout/Printing/SwiftLayoutPrinter.swift
  Tests/SwiftLayoutTests/AnchorsDSLTests.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
Labels: bug

#184 add ModularLayout
  Sources/SwiftLayout/Core/Layout/Layouts/ModularLayout.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
Labels: enhancement

#187 Feature/animatable layout property
  Sources/SwiftLayout/Layoutable/PropertyWrapper/AnimatableLayoutProperty.swift
  Tests/SwiftLayoutTests/LayoutBuildingTests.swift
Labels: enhancement

#186 re-architecting Anchors
  README.md
  README_ko.md
  Sources/SwiftLayout/Core/Anchors/Anchors.swift
  Sources/SwiftLayout/Core/Anchors/AnchorsAttribute.swift
  Sources/SwiftLayout/Core/Anchors/AnchorsContainer.swift
  Sources/SwiftLayout/Core/Anchors/AnchorsExpression.swift
  Sources/SwiftLayout/Core/Anchors/Constraint.swift
  Sources/SwiftLayout/Core/Anchors/ConstraintableItem.swift
  Sources/SwiftLayout/Core/Builder/AnchorsBuilder.swift
  Sources/SwiftLayout/Core/Layout/Layout.swift
  Sources/SwiftLayout/Core/Layout/LayoutExplorer.swift
  Sources/SwiftLayout/Core/Layout/Layouts/ViewLayout.swift
  Sources/SwiftLayout/Extension/Layout/UIVIew+Layout.swift
  Sources/SwiftLayout/Printing/Describe/Describer.swift
  Sources/SwiftLayout/Printing/Describe/Describer/AnchorsDescriber.swift
  Sources/SwiftLayout/Printing/Describe/Describer/ViewDescriber.swift
  Sources/SwiftLayout/Printing/Describe/Tag/ViewTags.swift
  Sources/SwiftLayout/Printing/Describe/Token/AnchorToken.swift
  Sources/SwiftLayout/Printing/Describe/Token/ViewToken.swift
  Sources/SwiftLayout/Printing/SwiftLayoutPrinter.swift
  Sources/SwiftLayout/Util/AddressDescriptor.swift
  Sources/SwiftLayout/Util/IdentifierUpdater.swift
  Tests/SwiftLayoutTests/AnchorsDSLTests.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/LayoutBuildingTests.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
Labels: enhancement

#189 subscripts for any object call self in some conditions
  Sources/SwiftLayout/Printing/Describe/Tag/ViewTags.swift
  Sources/SwiftLayout/Printing/Describe/Token/AnchorToken.swift
  Sources/SwiftLayout/Printing/Describe/Token/ViewToken.swift
Labels: bug

#188 Split the library into SwiftLayout and SwiftLayoutUtil
  .github/workflows/swift.yml
  Package.swift
  README.md
  README_ko.md
  Sources/SwiftLayout/Core/Anchors/Anchors.swift
  Sources/SwiftLayout/Core/Anchors/AnchorsContainer.swift
  Sources/SwiftLayout/Core/Anchors/Constraint.swift
  Sources/SwiftLayout/Core/Anchors/ConstraintableItem.swift
  Sources/SwiftLayout/Core/Anchors/Container/AnchorsContainer.swift
  Sources/SwiftLayout/Core/Anchors/Elements/AnchorsAttribute.swift
  Sources/SwiftLayout/Core/Anchors/Elements/AnchorsConstraintProperty.swift
  Sources/SwiftLayout/Core/Anchors/Elements/AnchorsExpression.swift
  Sources/SwiftLayout/Core/Anchors/Elements/AnchorsItem.swift
  Sources/SwiftLayout/Core/Builder/AnchorsBuilder.swift
  Sources/SwiftLayout/Core/Layout/Layout.swift
  Sources/SwiftLayout/Core/Layout/LayoutExplorer.swift
  Sources/SwiftLayout/Core/Layout/Layouts/ViewLayout.swift
  Sources/SwiftLayout/Core/Layout/ViewInformation.swift
  Sources/SwiftLayout/Extension/Set+Activation.swift
  Sources/SwiftLayout/Extension/UIVIew+Layout.swift
  Sources/SwiftLayout/Printing/SwiftLayoutPrinter.swift
  Sources/SwiftLayout/Util/WeakReference.swift
  Sources/SwiftLayoutUtil/Describe/Describer.swift
  Sources/SwiftLayoutUtil/Describe/Describer/AnchorsDescriber.swift
  Sources/SwiftLayoutUtil/Describe/Describer/ViewDescriber.swift
  Sources/SwiftLayoutUtil/Describe/Tag/ViewTags.swift
  Sources/SwiftLayoutUtil/Describe/Token/AnchorToken.swift
  Sources/SwiftLayoutUtil/Describe/Token/ViewToken.swift
  Sources/SwiftLayoutUtil/Extension/AnchorsItem+Description.swift
  Sources/SwiftLayoutUtil/Extension/Layout+Description.swift
  Sources/SwiftLayoutUtil/Extension/NSLayoutConstraint+Description.swift
  Sources/SwiftLayoutUtil/Extension/UILayoutGuide+Description.swift
  Sources/SwiftLayoutUtil/IdentifierUpdater.swift
  Sources/SwiftLayoutUtil/LayoutPrinter.swift
  Sources/SwiftLayoutUtil/Util/AddressDescriptor.swift
  Sources/SwiftLayoutUtil/Util/TagDescriptor.swift
  Sources/SwiftLayoutUtil/ViewPrinter.swift
  Tests/SwiftLayoutTests/AnchorsDSLTests.swift
  Tests/SwiftLayoutTests/ImplementationTests.swift
  Tests/SwiftLayoutTests/LayoutBuildingTests.swift
  Tests/SwiftLayoutTests/LayoutDSLTests.swift
  Tests/SwiftLayoutTests/PrintingTests.swift
  Tests/SwiftLayoutTests/Util/Extensions.swift
Labels: enhancement
